### ISSUE TITLE
Support Rize ETF/ARK Europe funds

### ISSUE THREAD

**Issue by MichaelDeBoey** [frefrik/ark-invest-api#230]
https://rizeetf.com/ark-acquisition
https://ark-funds.com/ark-invest-has-acquired-rize-etf

CC/ @frefrik

**Comment by MichaelDeBoey** [comment]
@frefrik any ETA on this?

**Comment by frefrik** [comment]
I thought I'd wait for the funds to rebrand to the ARK portfolio, but I see they've sort of done that now (https://europe.ark-funds.com). I'll see what I can do the coming days!

**Comment by frefrik** [comment]
I'm not quite sure what the correct name of the tickers should be, as they have different ticker names at different exchanges.

**Rize Sustainable Future of Food UCITS ETF** for example is listed with "Base Code" `FOOD`, but has the following actual tickers at different exchanges:
- FOOD IM
- RIZF GY
- FOOD NA
- FOOD LN
- FOGB LN
- ESSN SE

I guess we can use the "Base Code" in the [Funds overview](https://europe.ark-funds.com/funds/), but feel free to provide input.

<img width="719" alt="image" src="https://github.com/frefrik/ark-invest-api/assets/11590359/570081ae-b4b4-4c1a-87aa-e4fad66f62f2">
<img width="946" alt="image" src="https://github.com/frefrik/ark-invest-api/assets/11590359/e1caa2df-1d60-44f0-8057-d2727108b6b4">
<img width="857" alt="image" src="https://github.com/frefrik/ark-invest-api/assets/11590359/196ad615-b1e4-49b4-8b2f-9443805e6d27">
