### ISSUE TITLE
Stock Trades Query Params

### ISSUE THREAD

**Issue by siddharthgs** [frefrik/ark-invest-api#24]
Is it possible to add query params for date_from and date_to ?

I notice the historic trades don't go beyond "2020-09-18" - why is that ? 

https://arkfunds.io/api/v1/stock/trades?symbol=TSLA&date_from=2020-01-01

**Comment by frefrik** [comment]
Hi,

> Is it possible to add query params for date_from and date_to ?

Yes that should be possible!

> I notice the historic trades don't go beyond "2020-09-18" - why is that ?

Thats simply because its the oldest historic trades I have gathered and have access to.
If you know where I can scrape older trades feel free to let me know.
FYI, the oldest trades in the API db dates back to 2020-09-09.

**Comment by frefrik** [comment]
New query parameters (`date_from` and `date_to`) added to the Stock Trades endpoint!

Docs: https://github.com/frefrik/ark-invest-api#stock-trades
Example: https://arkfunds.io/api/v1/stock/trades?symbol=TSLA&date_from=2021-01-07&date_to=2021-01-12
