### ISSUE TITLE
Add backlog data for ARKVX

### ISSUE THREAD

**Issue by MichaelDeBoey** [frefrik/ark-invest-api#276]
As @NexVeridian mentioned in #231 

> I also have the backlog if you need that https://api.nexveridian.com/ark_holdings?ticker=ARKVX&start=2022-01-01

It would be nice if we could add this data here as well

CC/ @frefrik

**Comment by frefrik** [comment]
Fixed: https://arkfunds.io/api/v2/etf/holdings?symbol=arkvx&date_from=2022-01-01&date_to=2023-09-30
