### ISSUE TITLE
Url change for ark-funds.com

### ISSUE THREAD

**Issue by NexVeridian** [frefrik/ark-invest-api#278]
the website was update a few days ago
should probably change it if you haven't already
though the old one still works for now

`https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv`
to
`https://assets.ark-funds.com/fund-documents/funds-etf-csv/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv`

**Comment by NexVeridian** [comment]
And `ARKVX `

`https://ark-ventures.com/wp-content/uploads/funds-etf-csv/ARK_VENTURE_FUND_HOLDINGS.csv`
to
`https://assets.ark-funds.com/fund-documents/funds-etf-csv/ARK_VENTURE_FUND_ARKVX_HOLDINGS.csv`

**Comment by frefrik** [comment]
Thanks, yeah they are already updated.
Noticed it myself when my Actions started failing 😄
