### ISSUE TITLE
No data for May 01, 2021 onwards

### ISSUE THREAD

**Issue by tanNavarro** [frefrik/ark-invest-api#36]
The last data returned in the API https://arkfunds.io/api/v1/etf/trades is only on April 30, 2021 no data for May 01, 2021 onwards

https://www.loom.com/share/80361c9508e7455f9237d28599a282dd

**Comment by frefrik** [comment]
Fixed 👍🏻
The problem was that ARK released the trades later than the configured polling-window I use to get new trades.
The data is manually inserted now.
