### ISSUE TITLE
Add support for `PRNT`& `IZRL`

### ISSUE THREAD

**Issue by MichaelDeBoey** [frefrik/ark-invest-api#4]

**Comment by frefrik** [comment]
Support for `PRNT` and `IZRL` added!

**PRNT:** https://arkfunds.io/api/v1/etf/holdings?symbol=PRNT
**IZRL:** https://arkfunds.io/api/v1/etf/holdings?symbol=IZRL

I've also included historical data, dating back to 2020-11-24.
