### ISSUE TITLE
ETF holdings outdated

### ISSUE THREAD

**Issue by ohjason81** [frefrik/ark-invest-api#79]
The ETF holdings for all the funds except ARKK are from 2021-10-28.

Example:
https://arkfunds.io/api/v2/etf/holdings?symbol=ARKF&limit=3

**Comment by ohjason81** [comment]
Any updates on this?

**Comment by frefrik** [comment]
Hi, this was fixed yesterday.
The problem was that ARK had changed the filenames of their csv holding files.
