### ISSUE TITLE
Add support for `CTRU`

### ISSUE THREAD

**Issue by MichaelDeBoey** [frefrik/ark-invest-api#83]
https://ark-funds.com/funds/ctru

**Comment by frefrik** [comment]
Oh nice, will add support for this👍🏻

**Comment by MichaelDeBoey** [comment]
@frefrik 
- https://ark-funds.com/wp-content/uploads/funds-etf-pdf/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.pdf
- https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.csv

**Comment by frefrik** [comment]
Thx:)

Added `CTRU` now (https://github.com/frefrik/ark-invest-api/commit/125b3831b82e94b58178c90bfb02bb06f2d72f55):
https://arkfunds.io/api/v2/etf/profile?symbol=CTRU
https://arkfunds.io/api/v2/etf/holdings?symbol=CTRU
